* Higher-order functions

Higher-order functions should be familiar to most Python programmers. It should be obvious to most people that =foldr= in the paper corresponds to =functools.reduce= in Python.

Here we go a little further by extend =reduce= to trees.

** Representing trees

I'll represent a tree this way: =(label, [subtrees...])=: it's a tuple with a label (i.e., a leaf node) and a list of subtrees.

#+begin_src python :noweb yes :tangle src/test_foldtree.py
  import pytest
  from foldtree import *
  
  my_tree = (1, [
                 (2, []),
                 (3, [
                      (4, [])
                     ]
                  )
                 ])
#+end_src

** =foldtree()=: generalizing =reduce()= to trees

To generalize =reduce()= to trees, we have to specify two reduction functions (rather than one, as in =reduce=). The two functions are =f= for reducing a label and subtrees, and =g= for reducing subtrees. Both are functions of two arguments.

=a= is an initializing constant. 

#+begin_src python :noweb yes :tangle src/foldtree.py
  import operator


  def foldtree(f, g, a, tree_comp):
      if tree_comp == []:
          return a
      elif isinstance(tree_comp, list):
          # fold multiple subtrees
          subtree = tree_comp[0]
          rest = tree_comp[1:]
          return g(
                   foldtree(f, g, a, subtree),
                   foldtree(f, g, a, rest))
      else:
          assert isinstance(tree_comp, tuple)
          # fold a label with the subtrees
          (label, subtrees) = tree_comp
          return f(label,
                   foldtree(f, g, a, subtrees))
#+end_src

** Example #1: sum all labels (i.e., leaf nodes)

#+begin_src python :noweb yes :tangle src/foldtree.py
  def sumtree(tree):
      add = operator.add
      return foldtree(add, add, 0, tree)
#+end_src

#+begin_src python :noweb yes :tangle src/test_foldtree.py
  def test_sumtree():
      assert sumtree(my_tree) == 10
#+end_src

** Example #2: tree flattening

Collect all labels (i.e., leaf nodes) in a tree into a list.

#+begin_src python :noweb yes :tangle src/foldtree.py
  def tree_labels(tree):
      def cons(label, lst):
          return [label] + lst
      def append(lst1, lst2):
          return lst1 + lst2
      return foldtree(cons, append, [], tree)
#+end_src

#+begin_src python :noweb yes :tangle src/test_foldtree.py
  def test_tree_labels():
      assert tree_labels(my_tree) == [1, 2, 3, 4]
#+end_src

** Example #3: =map()= for trees

Map a function to all labels in a tree.

#+begin_src python :noweb yes :tangle src/foldtree.py
  def maptree(f, tree):
      def cons(leaf, lst):
          return [leaf] + lst

      def mk_leaf(leaf, lst):
          return (f(leaf), lst)
    
      return foldtree(mk_leaf, cons, [], tree)
#+end_src

#+begin_src python :noweb yes :tangle src/test_foldtree.py
  def test_maptree():
      res = maptree(lambda x: -1 * x, my_tree)
      res = tree_labels(res)
      assert res == [-1, -2, -3, -4]
#+end_src
