#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>
#+EXPORT_FILE_NAME: ../html/game.html
#+OPTIONS: broken-links:t
#+TITLE: Play games using lazy trees
In this chapter, we will apply the ideas developed so far to a more complicated problem: playing a two-player game. We'll develop the game AI code here, and then we'll use them to play Tic-tac-toe in the [[tic_tac_toe.org][next chapter]].

* Build a (lazy) game tree
Remember that =repeat_f= (defined [[newton.org][here]]) repeatedly applies a function to an initial value to generate a list. We'll extend the idea to trees. Let =f= be a function that takes a value, and returns a list of values. We define =reptree= to grows a tree out of an initial value by applying =f= repeatedly. Recall that tree is represented by =Node= defined in the [[lazy_tree.org][previous section]]. 
#+begin_src python :noweb yes :tangle ../src/lazy_utils.py
  def reptree(f: Callable[[Any], Optional[Iterator[Any]]], label: Any) -> Node:
      """Appy a function f to a label repeatedly to create a tree.
      f(label) is a list of labels
      """
      def make_children(lst):
          if lst is None:
              # f produces nothing
              return None
          else:
              # else, apply f repeatedly to elements of lst
              return map(lambda b: reptree(f, b), lst)

      return Node(label, make_children(f(label)))
#+end_src

For playing games, we represent the rules of the game in a function called =moves=. This function takes a initial state of the game board, and returns an iterator of board configurations corresponding to all legal moves (see [[tic_tac_toe.org][next chapter]] for a concrete example). By applying =moves= repeatedly to an initial board configuration, we get a tree of all possible future configurations of the game! Remember that =reptree= is lazy, so this large tree has not been created yet at this point. The future configurations will only be computed when they are needed.
#+begin_src python :noweb no-export :tangle ../src/game.py
  <<GAME_IMPORTS>>

  # Board is a type alias for representing a board configuration.
  # In this example,  it's just a list
  Board = List

  def gametree(moves: Callable[[Board], Optional[Iterator[Board]]]) -> Callable[[Board], Node]:
      """Return a func that builds a gametree from an initial board.
      moves is a function that returns all legal moves given a board.
      """
      def gametree_(board: Board) -> Node:
          return reptree(moves, board)
      return gametree_
#+end_src

The code above defines a =gametree= as "factory function", which receives =moves= and returns a closure that only needs the initial board configuration as its input. This way, it's easier to customized it for a specific game.

* Prune the game tree
To find the best next move, searching the entire game tree is typically impractical. We can reduce the size of the search space by limiting the game AI to look ahead only for a fixed number of moves. The =prune= function does this by removing nodes after a certain depth (=n=). 
#+begin_src python :noweb yes :tangle ../src/lazy_utils.py
  def prune(n: int, tree: Node) -> Node:
      """Remove nodes n levels below in the tree"""
      (board, subtrees) = tree

      if n == 0:
          return Node(board, None)
      elif subtrees is None:
          return Node(board, None)
      else:
          return Node(board, map(lambda t: prune(n - 1, t), subtrees))
#+end_src

* Static evaluation 
To play games, we need a static evaluation function to score each board configuration with a value, in order to guide the selection of the next move. This function does not take future moves into account, so it's not good enough for making the next move. But it's a good starting point.

The [[tic_tac_toe.org][next chapter]] customizes the code above to play Tic-tac-toe: =init_board= creates an empty game board, =gametree= creates a game tree, =prune= prunes a tree, and =static_eval(0)= scores a board configuration with a static evaluation function for player 0. The statement below replaces the labels in the game tree with the static scores. 
#+begin_src python
  maptree(static_eval(0), prune(gametree(init_board())))
#+end_src

Recall that =maptree= was defined in the [[lazy_tree.org][lazy tree chapter]].

* Minimax - the minimalist version
[[https://en.wikipedia.org/wiki/Minimax][Minimax]] is an algorithm for playing zero-sum two-player games. If a computer plays against a human opponent, Minimax selects the computer's best move in two steps: For every legal move that the computer can make, find the worst that the human can do to the computer in a follow-up move (this is the "min" step). Then take the move that is associated with the best outcome for the computer (the "max" step). But how does the computer know what's the worst that the human can do to it? It's the other side of the coin: It's the human's best move against the computer future moves. It's not hard to see that Minimax is naturally expressed as a pair of mutually recursive functions:

#+begin_src python :noweb yes :tangle ../src/game.py
  def maximize0(node: Node) -> int:
      """The max step of Minimax"""
      (score, subtrees) = node

      if subtrees is None:
          s = score
      else:
          s = max(map(minimize0, subtrees))
      return s

  def minimize0(node: Node) -> int:
      """The min step of Minimax"""    
      (score, subtrees) = node

      if subtrees is None:
          s = score
      else:
          s = min(map(maximize0, subtrees))
      return s
#+end_src

The code below is the first version of our tree evaluation function. Note that all the functions in the chain are lazy. Although the code reads like pruning, scoring, and minimaxing apply to the whole tree one function after another, in reality only the parts that are needed by the subsequent functions will be evaluated.
#+begin_src python :noweb yes :tangle ../src/game.py
  def evaluate0(gametree_: Callable[[Board], Node], static_eval_: Callable[[Board], int], prune_: Callable[[Node], Node]) -> Callable[[Board], int]:
      """Return a tree evaluation function"""
      def evaluate_(board: Board) -> int:
          return maximize0(maptree(static_eval_, prune_(gametree_(board))))
      return evaluate_
#+end_src

* Minimax - a more general version
The Minimax code in Hughes' paper is very minimalist (similar to =evaluate0=). It returns a score rather than a move. I'll expand it slightly. First, I want to store game board configurations in the labels in the game tree. It's done with a =State= class. Note that I implemented the rich comparison protocol, so that states can be compared just like numbers.  
#+begin_src python :noweb yes :tangle ../src/game.py
  @dataclass
  class State:
      board: Board
      score: int

      def __eq__(self, other):
          return self.score == other.score
      def __gt__(self, other):
          return self.score > other.score
      def __ge__(self, other):
          return self.score >= other.score
      def __lt__(self, other):
          return self.score < other.score
      def __le__(self, other):
          return self.score <= other.score
#+end_src

This updated version of Minimax is very similar to the one in the previous section, except for two changes: first, I decomposed =maximize0= into two functions: =maximized1_= only does and mapping, leaving =maximize1= to do the max. This decomposition will be useful in the next section. 
#+begin_src python :noweb yes :tangle ../src/game.py
  <<MISC_UTILS>>

  def maximize1_(node: Node) -> Iterator[State]:
      """The max step of Minimax before max"""
      (state, subtrees) = node

      if subtrees is None:
          yield state
      else:
          for s in map_(minimize1, subtrees):
              yield s

  def maximize1(node: Node) -> State:
      return max(maximize1_(node))

  def minimize1_(node: Node) -> Iterator[State]:
      """The min step of Minimax before min"""
      (state, subtrees) = node

      if subtrees is None:
          yield state
      else:
          for s in map_(maximize1, subtrees):
              yield s

  def minimize1(node: Node) -> State:
      return min(minimize1_(node))
#+end_src

Second, I replaced =map= with =map_=, which is very similar to the regular =map=, except that it takes care of the board configurations in the states. The board configurations returned from =func= are boards of the future. We'll replace them with just the moves under consideration. The definition is in Appendix 2.

This is the second version of the tree evaluation function:
#+begin_src python :noweb yes :tangle ../src/game.py
  def evaluate1(gametree_: Callable[[Board], Node], static_eval_: Callable[[Board], State], prune_: Callable[[Node], Node]) -> Callable[[Board], State]:
      """Return a tree evaluation function"""
      def evaluate_(board: Board) -> State:
          return maximize1(maptree(static_eval_, prune_(gametree_(board))))
      return evaluate_
#+end_src

* Alpha-beta pruning (using iterators of iterators)
Minimax visits every node in the game tree. Is there a way to avoid visiting branches that are obviously not promising?

Since this article is about programming rather than games, we'll go through the game AI part very briefly. The main goal of this section is to demonstrate that although we will modify the tree searching algorithm significantly, the structure of the code remains the same. It's very difficult to achieve this level of modularity if the algorithm is implemented with loops.

To make the search more efficient, step 1: recall that =maximize1_= calls =minimize1=, which means that =maximize1_= returns an iterator of values (technically, it's an iterator of States. But in each State is a single value, the score). Instead, we'll make it call =minimize1_=. This means that =maximize_= returns an iterator of iterators.

Step 2: There is a way to skip some of the iterators (at least partially). The trick is a pair of functions called =mapmin= and =mapmax=. I'll only describe what they do. The code is in Appendix 1. =mapmin= is just like =map(min, ...)=, except that it skips some unnecessary computation. How is it possible to skip any computation? Take this example: [[1, 2], [0, X]]. Following the logic of Minimax, we need the maximum of the two sublists' minima. The minimum of [1, 2] is 1. When we get to [0, X], we don't know the minimum, because X is unknown. However, we know that min([0, X])<=0. That means no matter what X is, min([0, X]) cannot be larger than the current max (which is 1). X therefore doesn't matter in the calculation of the max. If evaluation X is computationally demanding, this saves time.

This is the updated version of Minimax:
#+begin_src python :noweb no-export :tangle ../src/game.py
  <<ALPHA_BETA_UTILS>>

  def maximize2_(node: Node) -> Iterator[State]:
      """The max step of Minimax before max"""
      (state, subtrees) = node

      if subtrees is None:
          yield state
      else:
          #sutrees is an iterator of nodes
          for s in mapmin(map2_(minimize2_, subtrees)):
              yield s

  def maximize2(node: Node) -> State:
      return max(maximize2_(node))

  def minimize2_(node: Node) -> Iterator[State]:
      """The min step of Minimax before min"""
      (state, subtrees) = node

      if subtrees is None:
          yield state
      else:
          for s in mapmax(map2_(maximize2_, subtrees)):
              yield s

  def minimize2(node: Node) -> State:
      return min(minimize2_(node))
#+end_src
As in =maximize1_=, we need to modify the board configurations returned by =maximize2_= and =minimize2_=, because they would be boards of the future. This is done with =map2_= implemented in Appendix 2.

And the third version of the tree evaluation function:
#+begin_src python :noweb yes :tangle ../src/game.py
  def evaluate2(gametree_: Callable[[Board], Node], static_eval_: Callable[[Board], State], prune_: Callable[[Node], Node]) -> Callable[[Board], State]:
      """Return a tree evaluation function"""
      def evaluate_(board: Board) -> State:
          return maximize2(maptree(static_eval_, prune_(gametree_(board))))
      return evaluate_
#+end_src

* Appendix 1: Alpha-beta utilities
The heart of alpha-beta pruning is =mapmin=. It's just a more efficient version of =map(min, ...)= in the context of Minimax. To implement =mapmin=, we begin with =minleq=. Given an iterator =seq= and a "potential max" =mx= in a max step, =minleq(seq, mx)= returns if the iterator can be "omitted". For example, the following statement returns True.
#+begin_src python :exports both :noweb no-export :results value :dir ../src/
  <<DEMO_IMPORTS>>
  return minleq(iter([3, 2, 5, 30, 1, 6]), 20)
#+end_src

#+RESULTS:
: True

=minleq(itr, 20)= is looking for a value greater than 20. The first value of =itr= is 3, which means that the minimum of =itr= is not big enough to replace 20 as the potential maximum. The rest of the iterator therefore does not need to be evaluated further. The returned value =True= indicates that this sequence is to be omitted. In the context of games, this means that the max step is considering a move that doesn't need to be considered further, because the first potential counter-move that the opponent can make is already pretty bad for us (score=3). It's true that the 4th potential counter-move can be very good for us (score=30), but we can't count on the opponent making a blunder, can we?

The following statement, however, returns 1.
#+begin_src python :exports both :noweb no-export :results value :dir ../src/
  <<DEMO_IMPORTS>>
  return minleq(iter([3, 2, 5, 30, 1, 6]), 0)
#+end_src

#+RESULTS:
: 1

This sequence cannot be omitted because all numbers are larger than the potential max. In that case, the minimum (score=1) is returned. In the context of games, the max step is considering a move that is stronger than what had been considered before, because no matter what the counter-move is, we always end up in a better position.

Here's the code. See [[tests.org][here]] for more test cases.
#+begin_src python :tangle no :noweb-ref ALPHA_BETA_UTILS
  def mk_ab_seq(comp: Callable, op: Callable) -> Callable:
      """Given a comparison function comp and an operator op, return a function."""
      def ab_seq(seq: Optional[Iterator], pot: int) -> Optional[Union[int, bool]]:
          """Efficient min/max of an iterator, given potential max/min"""
          def ab_seq_(seq, current_val):
              try:
                  i = next(seq)
                  if current_val is None:
                      current_val = i

                  if comp(i, pot):
                      # if smaller, returns true immediately
                      return True
                  else:
                      return ab_seq_(seq, op(i, current_val))
              except StopIteration:
                  if current_val is None:
                      return pot
                  else:
                      return current_val

          if seq is None:
              return pot
          else:
              return ab_seq_(seq, None)

      return ab_seq

  minleq = mk_ab_seq(operator.le, min)
  minleq.__doc__ = """
  Return min of seq if it's > potential max.
  Else return True"""

  maxgeq = mk_ab_seq(operator.ge, max)
  maxgeq.__doc__ = """
  Return max of seq if it's < potential min.
  Else return True"""
#+end_src

With =minleq=, we can write =mapmin=. It takes a iterators of sub-iterators, and returns the minima of the sub-iterators, omitting the sub-iterators that don't matter. For example, the following code returns [1, 3]. Note that it is an increasing sequence.
#+begin_src python :exports both :noweb no-export :results value org :dir ../src/
  <<DEMO_IMPORTS>>
  seqs = iter([iter([1, 2]), iter([0, 10]), iter([3, 20]), iter([1, 100])])
  return list(mapmin(seqs))
#+end_src

#+RESULTS:
#+begin_src org
[1, 3]
#+end_src

Here's the implementation:
#+begin_src python :tangle no :noweb-ref ALPHA_BETA_UTILS
  def mapmin(seqs: Iterator[Iterator]) -> Iterator:
      """Like map(min, seqs)
      But skip those that don't matter for max.
      The sequence increases monotonically
      """
      try:
          seq = next(seqs)
          mn = min(seq)
          yield mn
          for i in omit_max(mn, seqs):
              yield i
      except StopIteration:
          pass

  def mapmax(seqs: Iterator[Iterator]) -> Iterator:
      """Like map(max, seqs)
      But skip those that don't matter for min
      The sequence decreases monotonically
      """
      try:
          seq = next(seqs)
          mx = max(seq)
          yield mx
          for i in omit_min(mx, seqs):
              yield i
      except StopIteration:
          pass

  def mk_omit(skip_func: Callable) -> Callable:
      """The skip function is either minleq or maxgeq"""
      def omit_(pot: int, seqs: Iterator[Iterator[int]]) -> Iterator[Optional[int]]:
          """Given an iterator of iterators, call skip_func.
          If the returned value is true, skip it. Otherwise, yield the value
          """
          for seq in seqs:
              m = skip_func(seq, pot)
              if m is True:
                  for i in omit_(pot, seqs):
                      yield i
              else:
                  yield m
                  for i in omit_(m, seqs):
                      yield i

      return omit_

  omit_max = mk_omit(minleq)
  omit_max.__doc__ = """
  Given an initial potential max, return the min of subsequences.
  Skip those that don't matter. Sequence increases.
  """

  omit_min = mk_omit(maxgeq)
  omit_max.__doc__ = """
  Given an initial potental min, return the max of subsequences.
  Skip those that don't matter. Sequence decreases.
  """
#+end_src

=mapmin=, =omit_max= and =minleq= are for the max step. Similarly, =mapmax=, =omit_min= and =maxgeq= are for the min step. 

* Appendix 2: Miscellaneous
Some tedious, hacky utilities:

#+begin_src python :tangle no :noweb-ref MISC_UTILS
  def map_(func: Callable[[Node], State], subtrees: Iterator[Node]) -> Iterator[State]:
      """Replace boards in an iterator with boards in subtrees"""
      assert subtrees is not None

      for subtree in subtrees:
          (state0, _) = subtree
          state1 = func(subtree)
          yield State(state0.board, state1.score)

  def replace_board(board: Board, itr: Iterator[State]):
      for state in itr:
          yield State(board, state.score)

  def map2_(func: Callable[[Node], Iterator[State]], subtrees: Iterator[Node]) -> Iterator[Iterator[State]]:
      """Replace boards in an iterator of iterators with boards in subtrees"""
      assert subtrees is not None

      for subtree in subtrees:
          (state0, _) = subtree
          yield replace_board(state0.board, func(subtree))
#+end_src

* Appendix 3: Imports
#+begin_src python :tangle no :noweb-ref GAME_IMPORTS
  from typing import Callable, List, Iterator, Optional, Union
  from dataclasses import dataclass 
  import operator

  from lazy_utils import reptree, maptree, Node
#+end_src

#+begin_src python :tangle no :noweb-ref DEMO_IMPORTS
  from game import minleq, mapmin
#+end_src
